server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
  # 默认情况下erureka server也是一个eureka client ,必须要指定一个 server
  # 通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.

    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
